name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [ ubuntu-latest ]
        jdk: [ 11 ]
    runs-on: ${{ matrix.os }}
    env:
      JDK_VERSION: ${{ matrix.jdk }}
    steps:
      - uses: actions/checkout@v3
      - name: setup jdk
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.jdk }}
          distribution: adopt
      - name: build with maven
        run: mvn --batch-mode --update-snapshots verify
